name: royalroad_api
description: Royalroad API
version: 0.2.2

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.12.0+4
  html: ^0.14.0+3
  intl: 0.16.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
