name: royalroad_api
description: Royalroad API
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:
#  path: ^1.6.0
dependencies:
  http: any
  html: any
  intl: any

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
